# Generated by Django 3.0.1 on 2020-01-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-date',), 'verbose_name': 'Activitie'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-Task_deadline',), 'verbose_name': 'Task'},
        ),
    ]
